/* SPDX-License-Identifier: MIT
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 * Copyright:
 *   2020      Evan Nemerson <evan@nemerson.com>
 *   2023      Yi-Yen Chung <eric681@andestech.com> (Copyright owned by Andes Technology)
 */

#if !defined(SIMDE_ARM_NEON_H)
#define SIMDE_ARM_NEON_H

#include <CppSimde/simde_arm_neon_types.hpp>

#include <CppSimde/simde_arm_neon_aba.hpp>
#include <CppSimde/simde_arm_neon_abal.hpp>
#include <CppSimde/simde_arm_neon_abal_high.hpp>
#include <CppSimde/simde_arm_neon_abd.hpp>
#include <CppSimde/simde_arm_neon_abdl.hpp>
#include <CppSimde/simde_arm_neon_abdl_high.hpp>
#include <CppSimde/simde_arm_neon_abs.hpp>
#include <CppSimde/simde_arm_neon_add.hpp>
#include <CppSimde/simde_arm_neon_addhn.hpp>
#include <CppSimde/simde_arm_neon_addhn_high.hpp>
#include <CppSimde/simde_arm_neon_addl.hpp>
#include <CppSimde/simde_arm_neon_addlv.hpp>
#include <CppSimde/simde_arm_neon_addl_high.hpp>
#include <CppSimde/simde_arm_neon_addv.hpp>
#include <CppSimde/simde_arm_neon_addw.hpp>
#include <CppSimde/simde_arm_neon_addw_high.hpp>
#include <CppSimde/simde_arm_neon_aes.hpp>
#include <CppSimde/simde_arm_neon_and.hpp>
#include <CppSimde/simde_arm_neon_bcax.hpp>
#include <CppSimde/simde_arm_neon_bic.hpp>
#include <CppSimde/simde_arm_neon_bsl.hpp>
#include <CppSimde/simde_arm_neon_cadd_rot270.hpp>
#include <CppSimde/simde_arm_neon_cadd_rot90.hpp>
#include <CppSimde/simde_arm_neon_cage.hpp>
#include <CppSimde/simde_arm_neon_cagt.hpp>
#include <CppSimde/simde_arm_neon_cale.hpp>
#include <CppSimde/simde_arm_neon_calt.hpp>
#include <CppSimde/simde_arm_neon_ceq.hpp>
#include <CppSimde/simde_arm_neon_ceqz.hpp>
#include <CppSimde/simde_arm_neon_cge.hpp>
#include <CppSimde/simde_arm_neon_cgez.hpp>
#include <CppSimde/simde_arm_neon_cgt.hpp>
#include <CppSimde/simde_arm_neon_cgtz.hpp>
#include <CppSimde/simde_arm_neon_cle.hpp>
#include <CppSimde/simde_arm_neon_clez.hpp>
#include <CppSimde/simde_arm_neon_cls.hpp>
#include <CppSimde/simde_arm_neon_clt.hpp>
#include <CppSimde/simde_arm_neon_cltz.hpp>
#include <CppSimde/simde_arm_neon_clz.hpp>
#include <CppSimde/simde_arm_neon_cmla.hpp>
#include <CppSimde/simde_arm_neon_cmla_lane.hpp>
#include <CppSimde/simde_arm_neon_cmla_rot180.hpp>
#include <CppSimde/simde_arm_neon_cmla_rot180_lane.hpp>
#include <CppSimde/simde_arm_neon_cmla_rot270.hpp>
#include <CppSimde/simde_arm_neon_cmla_rot270_lane.hpp>
#include <CppSimde/simde_arm_neon_cmla_rot90.hpp>
#include <CppSimde/simde_arm_neon_cmla_rot90_lane.hpp>
#include <CppSimde/simde_arm_neon_cnt.hpp>
#include <CppSimde/simde_arm_neon_cvt.hpp>
#include <CppSimde/simde_arm_neon_cvt_n.hpp>
#include <CppSimde/simde_arm_neon_cvtm.hpp>
#include <CppSimde/simde_arm_neon_cvtn.hpp>
#include <CppSimde/simde_arm_neon_cvtp.hpp>
#include <CppSimde/simde_arm_neon_combine.hpp>
#include <CppSimde/simde_arm_neon_copy_lane.hpp>
#include <CppSimde/simde_arm_neon_crc32.hpp>
#include <CppSimde/simde_arm_neon_create.hpp>
#include <CppSimde/simde_arm_neon_div.hpp>
#include <CppSimde/simde_arm_neon_dot.hpp>
#include <CppSimde/simde_arm_neon_dot_lane.hpp>
#include <CppSimde/simde_arm_neon_dup_lane.hpp>
#include <CppSimde/simde_arm_neon_dup_n.hpp>
#include <CppSimde/simde_arm_neon_eor.hpp>
#include <CppSimde/simde_arm_neon_ext.hpp>
#include <CppSimde/simde_arm_neon_fma.hpp>
#include <CppSimde/simde_arm_neon_fma_lane.hpp>
#include <CppSimde/simde_arm_neon_fma_n.hpp>
#include <CppSimde/simde_arm_neon_fmlal.hpp>
#include <CppSimde/simde_arm_neon_fmlsl.hpp>
#include <CppSimde/simde_arm_neon_fms.hpp>
#include <CppSimde/simde_arm_neon_fms_lane.hpp>
#include <CppSimde/simde_arm_neon_fms_n.hpp>
#include <CppSimde/simde_arm_neon_get_high.hpp>
#include <CppSimde/simde_arm_neon_get_lane.hpp>
#include <CppSimde/simde_arm_neon_get_low.hpp>
#include <CppSimde/simde_arm_neon_hadd.hpp>
#include <CppSimde/simde_arm_neon_hsub.hpp>
#include <CppSimde/simde_arm_neon_ld1.hpp>
#include <CppSimde/simde_arm_neon_ld1_dup.hpp>
#include <CppSimde/simde_arm_neon_ld1_lane.hpp>
#include <CppSimde/simde_arm_neon_ld1_x2.hpp>
#include <CppSimde/simde_arm_neon_ld1_x3.hpp>
#include <CppSimde/simde_arm_neon_ld1_x4.hpp>
#include <CppSimde/simde_arm_neon_ld1q_x2.hpp>
#include <CppSimde/simde_arm_neon_ld1q_x3.hpp>
#include <CppSimde/simde_arm_neon_ld1q_x4.hpp>
#include <CppSimde/simde_arm_neon_ld2.hpp>
#include <CppSimde/simde_arm_neon_ld2_dup.hpp>
#include <CppSimde/simde_arm_neon_ld2_lane.hpp>
#include <CppSimde/simde_arm_neon_ld3.hpp>
#include <CppSimde/simde_arm_neon_ld3_dup.hpp>
#include <CppSimde/simde_arm_neon_ld3_lane.hpp>
#include <CppSimde/simde_arm_neon_ld4.hpp>
#include <CppSimde/simde_arm_neon_ld4_dup.hpp>
#include <CppSimde/simde_arm_neon_ld4_lane.hpp>
#include <CppSimde/simde_arm_neon_max.hpp>
#include <CppSimde/simde_arm_neon_maxnm.hpp>
#include <CppSimde/simde_arm_neon_maxnmv.hpp>
#include <CppSimde/simde_arm_neon_maxv.hpp>
#include <CppSimde/simde_arm_neon_min.hpp>
#include <CppSimde/simde_arm_neon_minnm.hpp>
#include <CppSimde/simde_arm_neon_minnmv.hpp>
#include <CppSimde/simde_arm_neon_minv.hpp>
#include <CppSimde/simde_arm_neon_mla.hpp>
#include <CppSimde/simde_arm_neon_mla_lane.hpp>
#include <CppSimde/simde_arm_neon_mla_n.hpp>
#include <CppSimde/simde_arm_neon_mlal.hpp>
#include <CppSimde/simde_arm_neon_mlal_high.hpp>
#include <CppSimde/simde_arm_neon_mlal_high_lane.hpp>
#include <CppSimde/simde_arm_neon_mlal_high_n.hpp>
#include <CppSimde/simde_arm_neon_mlal_lane.hpp>
#include <CppSimde/simde_arm_neon_mlal_n.hpp>
#include <CppSimde/simde_arm_neon_mls.hpp>
#include <CppSimde/simde_arm_neon_mls_lane.hpp>
#include <CppSimde/simde_arm_neon_mls_n.hpp>
#include <CppSimde/simde_arm_neon_mlsl.hpp>
#include <CppSimde/simde_arm_neon_mlsl_high.hpp>
#include <CppSimde/simde_arm_neon_mlsl_high_lane.hpp>
#include <CppSimde/simde_arm_neon_mlsl_high_n.hpp>
#include <CppSimde/simde_arm_neon_mlsl_lane.hpp>
#include <CppSimde/simde_arm_neon_mlsl_n.hpp>
#include <CppSimde/simde_arm_neon_mmlaq.hpp>
#include <CppSimde/simde_arm_neon_movl.hpp>
#include <CppSimde/simde_arm_neon_movl_high.hpp>
#include <CppSimde/simde_arm_neon_movn.hpp>
#include <CppSimde/simde_arm_neon_movn_high.hpp>
#include <CppSimde/simde_arm_neon_mul.hpp>
#include <CppSimde/simde_arm_neon_mul_lane.hpp>
#include <CppSimde/simde_arm_neon_mul_n.hpp>
#include <CppSimde/simde_arm_neon_mull.hpp>
#include <CppSimde/simde_arm_neon_mull_high.hpp>
#include <CppSimde/simde_arm_neon_mull_high_lane.hpp>
#include <CppSimde/simde_arm_neon_mull_high_n.hpp>
#include <CppSimde/simde_arm_neon_mull_lane.hpp>
#include <CppSimde/simde_arm_neon_mull_n.hpp>
#include <CppSimde/simde_arm_neon_mulx.hpp>
#include <CppSimde/simde_arm_neon_mulx_lane.hpp>
#include <CppSimde/simde_arm_neon_mulx_n.hpp>
#include <CppSimde/simde_arm_neon_mvn.hpp>
#include <CppSimde/simde_arm_neon_neg.hpp>
#include <CppSimde/simde_arm_neon_orn.hpp>
#include <CppSimde/simde_arm_neon_orr.hpp>
#include <CppSimde/simde_arm_neon_padal.hpp>
#include <CppSimde/simde_arm_neon_padd.hpp>
#include <CppSimde/simde_arm_neon_paddl.hpp>
#include <CppSimde/simde_arm_neon_pmax.hpp>
#include <CppSimde/simde_arm_neon_pmaxnm.hpp>
#include <CppSimde/simde_arm_neon_pmin.hpp>
#include <CppSimde/simde_arm_neon_pminnm.hpp>
#include <CppSimde/simde_arm_neon_qabs.hpp>
#include <CppSimde/simde_arm_neon_qadd.hpp>
#include <CppSimde/simde_arm_neon_qdmlal.hpp>
#include <CppSimde/simde_arm_neon_qdmlal_high.hpp>
#include <CppSimde/simde_arm_neon_qdmlal_high_lane.hpp>
#include <CppSimde/simde_arm_neon_qdmlal_high_n.hpp>
#include <CppSimde/simde_arm_neon_qdmlal_lane.hpp>
#include <CppSimde/simde_arm_neon_qdmlal_n.hpp>
#include <CppSimde/simde_arm_neon_qdmlsl.hpp>
#include <CppSimde/simde_arm_neon_qdmlsl_high.hpp>
#include <CppSimde/simde_arm_neon_qdmlsl_high_lane.hpp>
#include <CppSimde/simde_arm_neon_qdmlsl_high_n.hpp>
#include <CppSimde/simde_arm_neon_qdmlsl_lane.hpp>
#include <CppSimde/simde_arm_neon_qdmlsl_n.hpp>
#include <CppSimde/simde_arm_neon_qdmulh.hpp>
#include <CppSimde/simde_arm_neon_qdmulh_lane.hpp>
#include <CppSimde/simde_arm_neon_qdmulh_n.hpp>
#include <CppSimde/simde_arm_neon_qdmull.hpp>
#include <CppSimde/simde_arm_neon_qdmull_high.hpp>
#include <CppSimde/simde_arm_neon_qdmull_high_lane.hpp>
#include <CppSimde/simde_arm_neon_qdmull_high_n.hpp>
#include <CppSimde/simde_arm_neon_qdmull_lane.hpp>
#include <CppSimde/simde_arm_neon_qdmull_n.hpp>
#include <CppSimde/simde_arm_neon_qrdmlah.hpp>
#include <CppSimde/simde_arm_neon_qrdmlah_lane.hpp>
#include <CppSimde/simde_arm_neon_qrdmlsh.hpp>
#include <CppSimde/simde_arm_neon_qrdmlsh_lane.hpp>
#include <CppSimde/simde_arm_neon_qrdmulh.hpp>
#include <CppSimde/simde_arm_neon_qrdmulh_lane.hpp>
#include <CppSimde/simde_arm_neon_qrdmulh_n.hpp>
#include <CppSimde/simde_arm_neon_qrshl.hpp>
#include <CppSimde/simde_arm_neon_qrshrn_high_n.hpp>
#include <CppSimde/simde_arm_neon_qrshrn_n.hpp>
#include <CppSimde/simde_arm_neon_qrshrun_high_n.hpp>
#include <CppSimde/simde_arm_neon_qrshrun_n.hpp>
#include <CppSimde/simde_arm_neon_qmovn.hpp>
#include <CppSimde/simde_arm_neon_qmovn_high.hpp>
#include <CppSimde/simde_arm_neon_qmovun.hpp>
#include <CppSimde/simde_arm_neon_qmovun_high.hpp>
#include <CppSimde/simde_arm_neon_qneg.hpp>
#include <CppSimde/simde_arm_neon_qsub.hpp>
#include <CppSimde/simde_arm_neon_qshl.hpp>
#include <CppSimde/simde_arm_neon_qshl_n.hpp>
#include <CppSimde/simde_arm_neon_qshlu_n.hpp>
#include <CppSimde/simde_arm_neon_qshrn_high_n.hpp>
#include <CppSimde/simde_arm_neon_qshrn_n.hpp>
#include <CppSimde/simde_arm_neon_qshrun_high_n.hpp>
#include <CppSimde/simde_arm_neon_qshrun_n.hpp>
#include <CppSimde/simde_arm_neon_qtbl.hpp>
#include <CppSimde/simde_arm_neon_qtbx.hpp>
#include <CppSimde/simde_arm_neon_raddhn.hpp>
#include <CppSimde/simde_arm_neon_raddhn_high.hpp>
#include <CppSimde/simde_arm_neon_rax.hpp>
#include <CppSimde/simde_arm_neon_rbit.hpp>
#include <CppSimde/simde_arm_neon_recpe.hpp>
#include <CppSimde/simde_arm_neon_recps.hpp>
#include <CppSimde/simde_arm_neon_recpx.hpp>
#include <CppSimde/simde_arm_neon_reinterpret.hpp>
#include <CppSimde/simde_arm_neon_rev16.hpp>
#include <CppSimde/simde_arm_neon_rev32.hpp>
#include <CppSimde/simde_arm_neon_rev64.hpp>
#include <CppSimde/simde_arm_neon_rhadd.hpp>
#include <CppSimde/simde_arm_neon_rnd.hpp>
#include <CppSimde/simde_arm_neon_rnd32x.hpp>
#include <CppSimde/simde_arm_neon_rnd32z.hpp>
#include <CppSimde/simde_arm_neon_rnd64x.hpp>
#include <CppSimde/simde_arm_neon_rnd64z.hpp>
#include <CppSimde/simde_arm_neon_rnda.hpp>
#include <CppSimde/simde_arm_neon_rndm.hpp>
#include <CppSimde/simde_arm_neon_rndi.hpp>
#include <CppSimde/simde_arm_neon_rndn.hpp>
#include <CppSimde/simde_arm_neon_rndp.hpp>
#include <CppSimde/simde_arm_neon_rndx.hpp>
#include <CppSimde/simde_arm_neon_rshl.hpp>
#include <CppSimde/simde_arm_neon_rshr_n.hpp>
#include <CppSimde/simde_arm_neon_rshrn_high_n.hpp>
#include <CppSimde/simde_arm_neon_rshrn_n.hpp>
#include <CppSimde/simde_arm_neon_rsqrte.hpp>
#include <CppSimde/simde_arm_neon_rsqrts.hpp>
#include <CppSimde/simde_arm_neon_rsra_n.hpp>
#include <CppSimde/simde_arm_neon_rsubhn.hpp>
#include <CppSimde/simde_arm_neon_rsubhn_high.hpp>
#include <CppSimde/simde_arm_neon_set_lane.hpp>
#include <CppSimde/simde_arm_neon_sha1.hpp>
#include <CppSimde/simde_arm_neon_sha256.hpp>
#include <CppSimde/simde_arm_neon_sha512.hpp>
#include <CppSimde/simde_arm_neon_shl.hpp>
#include <CppSimde/simde_arm_neon_shl_n.hpp>
#include <CppSimde/simde_arm_neon_shll_high_n.hpp>
#include <CppSimde/simde_arm_neon_shll_n.hpp>
#include <CppSimde/simde_arm_neon_shr_n.hpp>
#include <CppSimde/simde_arm_neon_shrn_high_n.hpp>
#include <CppSimde/simde_arm_neon_shrn_n.hpp>
#include <CppSimde/simde_arm_neon_sli_n.hpp>
#include <CppSimde/simde_arm_neon_sm3.hpp>
#include <CppSimde/simde_arm_neon_sm4.hpp>
#include <CppSimde/simde_arm_neon_sqadd.hpp>
#include <CppSimde/simde_arm_neon_sqrt.hpp>
#include <CppSimde/simde_arm_neon_sra_n.hpp>
#include <CppSimde/simde_arm_neon_sri_n.hpp>
#include <CppSimde/simde_arm_neon_st1.hpp>
#include <CppSimde/simde_arm_neon_st1_lane.hpp>
#include <CppSimde/simde_arm_neon_st1_x2.hpp>
#include <CppSimde/simde_arm_neon_st1_x3.hpp>
#include <CppSimde/simde_arm_neon_st1_x4.hpp>
#include <CppSimde/simde_arm_neon_st1q_x2.hpp>
#include <CppSimde/simde_arm_neon_st1q_x3.hpp>
#include <CppSimde/simde_arm_neon_st1q_x4.hpp>
#include <CppSimde/simde_arm_neon_st2.hpp>
#include <CppSimde/simde_arm_neon_st2_lane.hpp>
#include <CppSimde/simde_arm_neon_st3.hpp>
#include <CppSimde/simde_arm_neon_st3_lane.hpp>
#include <CppSimde/simde_arm_neon_st4.hpp>
#include <CppSimde/simde_arm_neon_st4_lane.hpp>
#include <CppSimde/simde_arm_neon_sub.hpp>
#include <CppSimde/simde_arm_neon_subhn.hpp>
#include <CppSimde/simde_arm_neon_subhn_high.hpp>
#include <CppSimde/simde_arm_neon_subl.hpp>
#include <CppSimde/simde_arm_neon_subl_high.hpp>
#include <CppSimde/simde_arm_neon_subw.hpp>
#include <CppSimde/simde_arm_neon_subw_high.hpp>
#include <CppSimde/simde_arm_neon_sudot_lane.hpp>
#include <CppSimde/simde_arm_neon_tbl.hpp>
#include <CppSimde/simde_arm_neon_tbx.hpp>
#include <CppSimde/simde_arm_neon_trn.hpp>
#include <CppSimde/simde_arm_neon_trn1.hpp>
#include <CppSimde/simde_arm_neon_trn2.hpp>
#include <CppSimde/simde_arm_neon_tst.hpp>
#include <CppSimde/simde_arm_neon_uqadd.hpp>
#include <CppSimde/simde_arm_neon_usdot.hpp>
#include <CppSimde/simde_arm_neon_usdot_lane.hpp>
#include <CppSimde/simde_arm_neon_uzp.hpp>
#include <CppSimde/simde_arm_neon_uzp1.hpp>
#include <CppSimde/simde_arm_neon_uzp2.hpp>
#include <CppSimde/simde_arm_neon_xar.hpp>
#include <CppSimde/simde_arm_neon_zip.hpp>
#include <CppSimde/simde_arm_neon_zip1.hpp>
#include <CppSimde/simde_arm_neon_zip2.hpp>

#endif /* SIMDE_ARM_NEON_H */

