//
//  CppSimde.h
//  CppSimde
//
//  Created by Undo Hatsune on 2024/03/10.
//

#import <Foundation/Foundation.h>

//! Project version number for CppSimde.
FOUNDATION_EXPORT double CppSimdeVersionNumber;

//! Project version string for CppSimde.
FOUNDATION_EXPORT const unsigned char CppSimdeVersionString[];

// In this header, you should import all the public headers of your framework using statements like #import <CppSimde/PublicHeader.h>


#import <CppSimde/simde_arm_neon_aba.hpp>
#import <CppSimde/simde_arm_neon_abal.hpp>
#import <CppSimde/simde_arm_neon_abal_high.hpp>
#import <CppSimde/simde_arm_neon_abd.hpp>
#import <CppSimde/simde_arm_neon_abdl.hpp>
#import <CppSimde/simde_arm_neon_abdl_high.hpp>
#import <CppSimde/simde_arm_neon_abs.hpp>
#import <CppSimde/simde_arm_neon_add.hpp>
#import <CppSimde/simde_arm_neon_addhn.hpp>
#import <CppSimde/simde_arm_neon_addhn_high.hpp>
#import <CppSimde/simde_arm_neon_addl.hpp>
#import <CppSimde/simde_arm_neon_addl_high.hpp>
#import <CppSimde/simde_arm_neon_addlv.hpp>
#import <CppSimde/simde_arm_neon_addv.hpp>
#import <CppSimde/simde_arm_neon_addw.hpp>
#import <CppSimde/simde_arm_neon_addw_high.hpp>
#import <CppSimde/simde_arm_neon_aes.hpp>
#import <CppSimde/simde_arm_neon_and.hpp>
#import <CppSimde/simde_arm_neon_bcax.hpp>
#import <CppSimde/simde_arm_neon_bic.hpp>
#import <CppSimde/simde_arm_neon_bsl.hpp>
#import <CppSimde/simde_arm_neon_cadd_rot270.hpp>
#import <CppSimde/simde_arm_neon_cadd_rot90.hpp>
#import <CppSimde/simde_arm_neon_cage.hpp>
#import <CppSimde/simde_arm_neon_cagt.hpp>
#import <CppSimde/simde_arm_neon_cale.hpp>
#import <CppSimde/simde_arm_neon_calt.hpp>
#import <CppSimde/simde_arm_neon_ceq.hpp>
#import <CppSimde/simde_arm_neon_ceqz.hpp>
#import <CppSimde/simde_arm_neon_cge.hpp>
#import <CppSimde/simde_arm_neon_cgez.hpp>
#import <CppSimde/simde_arm_neon_cgt.hpp>
#import <CppSimde/simde_arm_neon_cgtz.hpp>
#import <CppSimde/simde_arm_neon_cle.hpp>
#import <CppSimde/simde_arm_neon_clez.hpp>
#import <CppSimde/simde_arm_neon_cls.hpp>
#import <CppSimde/simde_arm_neon_clt.hpp>
#import <CppSimde/simde_arm_neon_cltz.hpp>
#import <CppSimde/simde_arm_neon_clz.hpp>
#import <CppSimde/simde_arm_neon_cmla.hpp>
#import <CppSimde/simde_arm_neon_cmla_lane.hpp>
#import <CppSimde/simde_arm_neon_cmla_rot180.hpp>
#import <CppSimde/simde_arm_neon_cmla_rot180_lane.hpp>
#import <CppSimde/simde_arm_neon_cmla_rot270.hpp>
#import <CppSimde/simde_arm_neon_cmla_rot270_lane.hpp>
#import <CppSimde/simde_arm_neon_cmla_rot90.hpp>
#import <CppSimde/simde_arm_neon_cmla_rot90_lane.hpp>
#import <CppSimde/simde_arm_neon_cnt.hpp>
#import <CppSimde/simde_arm_neon_combine.hpp>
#import <CppSimde/simde_arm_neon_copy_lane.hpp>
#import <CppSimde/simde_arm_neon_crc32.hpp>
#import <CppSimde/simde_arm_neon_create.hpp>
#import <CppSimde/simde_arm_neon_cvt.hpp>
#import <CppSimde/simde_arm_neon_cvt_n.hpp>
#import <CppSimde/simde_arm_neon_cvtm.hpp>
#import <CppSimde/simde_arm_neon_cvtn.hpp>
#import <CppSimde/simde_arm_neon_cvtp.hpp>
#import <CppSimde/simde_arm_neon_div.hpp>
#import <CppSimde/simde_arm_neon_dot.hpp>
#import <CppSimde/simde_arm_neon_dot_lane.hpp>
#import <CppSimde/simde_arm_neon_dup_lane.hpp>
#import <CppSimde/simde_arm_neon_dup_n.hpp>
#import <CppSimde/simde_arm_neon_eor.hpp>
#import <CppSimde/simde_arm_neon_ext.hpp>
#import <CppSimde/simde_arm_neon_fma.hpp>
#import <CppSimde/simde_arm_neon_fma_lane.hpp>
#import <CppSimde/simde_arm_neon_fma_n.hpp>
#import <CppSimde/simde_arm_neon_fmlal.hpp>
#import <CppSimde/simde_arm_neon_fmlsl.hpp>
#import <CppSimde/simde_arm_neon_fms.hpp>
#import <CppSimde/simde_arm_neon_fms_lane.hpp>
#import <CppSimde/simde_arm_neon_fms_n.hpp>
#import <CppSimde/simde_arm_neon_get_high.hpp>
#import <CppSimde/simde_arm_neon_get_lane.hpp>
#import <CppSimde/simde_arm_neon_get_low.hpp>
#import <CppSimde/simde_arm_neon_hadd.hpp>
#import <CppSimde/simde_arm_neon_hsub.hpp>
#import <CppSimde/simde_arm_neon_ld1.hpp>
#import <CppSimde/simde_arm_neon_ld1_dup.hpp>
#import <CppSimde/simde_arm_neon_ld1_lane.hpp>
#import <CppSimde/simde_arm_neon_ld1_x2.hpp>
#import <CppSimde/simde_arm_neon_ld1_x3.hpp>
#import <CppSimde/simde_arm_neon_ld1_x4.hpp>
#import <CppSimde/simde_arm_neon_ld1q_x2.hpp>
#import <CppSimde/simde_arm_neon_ld1q_x3.hpp>
#import <CppSimde/simde_arm_neon_ld1q_x4.hpp>
#import <CppSimde/simde_arm_neon_ld2.hpp>
#import <CppSimde/simde_arm_neon_ld2_dup.hpp>
#import <CppSimde/simde_arm_neon_ld2_lane.hpp>
#import <CppSimde/simde_arm_neon_ld3.hpp>
#import <CppSimde/simde_arm_neon_ld3_dup.hpp>
#import <CppSimde/simde_arm_neon_ld3_lane.hpp>
#import <CppSimde/simde_arm_neon_ld4.hpp>
#import <CppSimde/simde_arm_neon_ld4_dup.hpp>
#import <CppSimde/simde_arm_neon_ld4_lane.hpp>
#import <CppSimde/simde_arm_neon_max.hpp>
#import <CppSimde/simde_arm_neon_maxnm.hpp>
#import <CppSimde/simde_arm_neon_maxnmv.hpp>
#import <CppSimde/simde_arm_neon_maxv.hpp>
#import <CppSimde/simde_arm_neon_min.hpp>
#import <CppSimde/simde_arm_neon_minnm.hpp>
#import <CppSimde/simde_arm_neon_minnmv.hpp>
#import <CppSimde/simde_arm_neon_minv.hpp>
#import <CppSimde/simde_arm_neon_mla.hpp>
#import <CppSimde/simde_arm_neon_mla_lane.hpp>
#import <CppSimde/simde_arm_neon_mla_n.hpp>
#import <CppSimde/simde_arm_neon_mlal.hpp>
#import <CppSimde/simde_arm_neon_mlal_high.hpp>
#import <CppSimde/simde_arm_neon_mlal_high_lane.hpp>
#import <CppSimde/simde_arm_neon_mlal_high_n.hpp>
#import <CppSimde/simde_arm_neon_mlal_lane.hpp>
#import <CppSimde/simde_arm_neon_mlal_n.hpp>
#import <CppSimde/simde_arm_neon_mls.hpp>
#import <CppSimde/simde_arm_neon_mls_lane.hpp>
#import <CppSimde/simde_arm_neon_mls_n.hpp>
#import <CppSimde/simde_arm_neon_mlsl.hpp>
#import <CppSimde/simde_arm_neon_mlsl_high.hpp>
#import <CppSimde/simde_arm_neon_mlsl_high_lane.hpp>
#import <CppSimde/simde_arm_neon_mlsl_high_n.hpp>
#import <CppSimde/simde_arm_neon_mlsl_lane.hpp>
#import <CppSimde/simde_arm_neon_mlsl_n.hpp>
#import <CppSimde/simde_arm_neon_mmlaq.hpp>
#import <CppSimde/simde_arm_neon_movl.hpp>
#import <CppSimde/simde_arm_neon_movl_high.hpp>
#import <CppSimde/simde_arm_neon_movn.hpp>
#import <CppSimde/simde_arm_neon_movn_high.hpp>
#import <CppSimde/simde_arm_neon_mul.hpp>
#import <CppSimde/simde_arm_neon_mul_lane.hpp>
#import <CppSimde/simde_arm_neon_mul_n.hpp>
#import <CppSimde/simde_arm_neon_mull.hpp>
#import <CppSimde/simde_arm_neon_mull_high.hpp>
#import <CppSimde/simde_arm_neon_mull_high_lane.hpp>
#import <CppSimde/simde_arm_neon_mull_high_n.hpp>
#import <CppSimde/simde_arm_neon_mull_lane.hpp>
#import <CppSimde/simde_arm_neon_mull_n.hpp>
#import <CppSimde/simde_arm_neon_mulx.hpp>
#import <CppSimde/simde_arm_neon_mulx_lane.hpp>
#import <CppSimde/simde_arm_neon_mulx_n.hpp>
#import <CppSimde/simde_arm_neon_mvn.hpp>
#import <CppSimde/simde_arm_neon_neg.hpp>
#import <CppSimde/simde_arm_neon_orn.hpp>
#import <CppSimde/simde_arm_neon_orr.hpp>
#import <CppSimde/simde_arm_neon_padal.hpp>
#import <CppSimde/simde_arm_neon_padd.hpp>
#import <CppSimde/simde_arm_neon_paddl.hpp>
#import <CppSimde/simde_arm_neon_pmax.hpp>
#import <CppSimde/simde_arm_neon_pmaxnm.hpp>
#import <CppSimde/simde_arm_neon_pmin.hpp>
#import <CppSimde/simde_arm_neon_pminnm.hpp>
#import <CppSimde/simde_arm_neon_qabs.hpp>
#import <CppSimde/simde_arm_neon_qadd.hpp>
#import <CppSimde/simde_arm_neon_qdmlal.hpp>
#import <CppSimde/simde_arm_neon_qdmlal_high.hpp>
#import <CppSimde/simde_arm_neon_qdmlal_high_lane.hpp>
#import <CppSimde/simde_arm_neon_qdmlal_high_n.hpp>
#import <CppSimde/simde_arm_neon_qdmlal_lane.hpp>
#import <CppSimde/simde_arm_neon_qdmlal_n.hpp>
#import <CppSimde/simde_arm_neon_qdmlsl.hpp>
#import <CppSimde/simde_arm_neon_qdmlsl_high.hpp>
#import <CppSimde/simde_arm_neon_qdmlsl_high_lane.hpp>
#import <CppSimde/simde_arm_neon_qdmlsl_high_n.hpp>
#import <CppSimde/simde_arm_neon_qdmlsl_lane.hpp>
#import <CppSimde/simde_arm_neon_qdmlsl_n.hpp>
#import <CppSimde/simde_arm_neon_qdmulh.hpp>
#import <CppSimde/simde_arm_neon_qdmulh_lane.hpp>
#import <CppSimde/simde_arm_neon_qdmulh_n.hpp>
#import <CppSimde/simde_arm_neon_qdmull.hpp>
#import <CppSimde/simde_arm_neon_qdmull_high.hpp>
#import <CppSimde/simde_arm_neon_qdmull_high_lane.hpp>
#import <CppSimde/simde_arm_neon_qdmull_high_n.hpp>
#import <CppSimde/simde_arm_neon_qdmull_lane.hpp>
#import <CppSimde/simde_arm_neon_qdmull_n.hpp>
#import <CppSimde/simde_arm_neon_qmovn.hpp>
#import <CppSimde/simde_arm_neon_qmovn_high.hpp>
#import <CppSimde/simde_arm_neon_qmovun.hpp>
#import <CppSimde/simde_arm_neon_qmovun_high.hpp>
#import <CppSimde/simde_arm_neon_qneg.hpp>
#import <CppSimde/simde_arm_neon_qrdmlah.hpp>
#import <CppSimde/simde_arm_neon_qrdmlah_lane.hpp>
#import <CppSimde/simde_arm_neon_qrdmlsh.hpp>
#import <CppSimde/simde_arm_neon_qrdmlsh_lane.hpp>
#import <CppSimde/simde_arm_neon_qrdmulh.hpp>
#import <CppSimde/simde_arm_neon_qrdmulh_lane.hpp>
#import <CppSimde/simde_arm_neon_qrdmulh_n.hpp>
#import <CppSimde/simde_arm_neon_qrshl.hpp>
#import <CppSimde/simde_arm_neon_qrshrn_high_n.hpp>
#import <CppSimde/simde_arm_neon_qrshrn_n.hpp>
#import <CppSimde/simde_arm_neon_qrshrun_high_n.hpp>
#import <CppSimde/simde_arm_neon_qrshrun_n.hpp>
#import <CppSimde/simde_arm_neon_qshl.hpp>
#import <CppSimde/simde_arm_neon_qshl_n.hpp>
#import <CppSimde/simde_arm_neon_qshlu_n.hpp>
#import <CppSimde/simde_arm_neon_qshrn_high_n.hpp>
#import <CppSimde/simde_arm_neon_qshrn_n.hpp>
#import <CppSimde/simde_arm_neon_qshrun_high_n.hpp>
#import <CppSimde/simde_arm_neon_qshrun_n.hpp>
#import <CppSimde/simde_arm_neon_qsub.hpp>
#import <CppSimde/simde_arm_neon_qtbl.hpp>
#import <CppSimde/simde_arm_neon_qtbx.hpp>
#import <CppSimde/simde_arm_neon_raddhn.hpp>
#import <CppSimde/simde_arm_neon_raddhn_high.hpp>
#import <CppSimde/simde_arm_neon_rax.hpp>
#import <CppSimde/simde_arm_neon_rbit.hpp>
#import <CppSimde/simde_arm_neon_recpe.hpp>
#import <CppSimde/simde_arm_neon_recps.hpp>
#import <CppSimde/simde_arm_neon_recpx.hpp>
#import <CppSimde/simde_arm_neon_reinterpret.hpp>
#import <CppSimde/simde_arm_neon_rev16.hpp>
#import <CppSimde/simde_arm_neon_rev32.hpp>
#import <CppSimde/simde_arm_neon_rev64.hpp>
#import <CppSimde/simde_arm_neon_rhadd.hpp>
#import <CppSimde/simde_arm_neon_rnd.hpp>
#import <CppSimde/simde_arm_neon_rnd32x.hpp>
#import <CppSimde/simde_arm_neon_rnd32z.hpp>
#import <CppSimde/simde_arm_neon_rnd64x.hpp>
#import <CppSimde/simde_arm_neon_rnd64z.hpp>
#import <CppSimde/simde_arm_neon_rnda.hpp>
#import <CppSimde/simde_arm_neon_rndi.hpp>
#import <CppSimde/simde_arm_neon_rndm.hpp>
#import <CppSimde/simde_arm_neon_rndn.hpp>
#import <CppSimde/simde_arm_neon_rndp.hpp>
#import <CppSimde/simde_arm_neon_rndx.hpp>
#import <CppSimde/simde_arm_neon_rshl.hpp>
#import <CppSimde/simde_arm_neon_rshr_n.hpp>
#import <CppSimde/simde_arm_neon_rshrn_high_n.hpp>
#import <CppSimde/simde_arm_neon_rshrn_n.hpp>
#import <CppSimde/simde_arm_neon_rsqrte.hpp>
#import <CppSimde/simde_arm_neon_rsqrts.hpp>
#import <CppSimde/simde_arm_neon_rsra_n.hpp>
#import <CppSimde/simde_arm_neon_rsubhn.hpp>
#import <CppSimde/simde_arm_neon_rsubhn_high.hpp>
#import <CppSimde/simde_arm_neon_set_lane.hpp>
#import <CppSimde/simde_arm_neon_sha1.hpp>
#import <CppSimde/simde_arm_neon_sha256.hpp>
#import <CppSimde/simde_arm_neon_sha512.hpp>
#import <CppSimde/simde_arm_neon_shl.hpp>
#import <CppSimde/simde_arm_neon_shl_n.hpp>
#import <CppSimde/simde_arm_neon_shll_high_n.hpp>
#import <CppSimde/simde_arm_neon_shll_n.hpp>
#import <CppSimde/simde_arm_neon_shr_n.hpp>
#import <CppSimde/simde_arm_neon_shrn_high_n.hpp>
#import <CppSimde/simde_arm_neon_shrn_n.hpp>
#import <CppSimde/simde_arm_neon_sli_n.hpp>
#import <CppSimde/simde_arm_neon_sm3.hpp>
#import <CppSimde/simde_arm_neon_sm4.hpp>
#import <CppSimde/simde_arm_neon_sqadd.hpp>
#import <CppSimde/simde_arm_neon_sqrt.hpp>
#import <CppSimde/simde_arm_neon_sra_n.hpp>
#import <CppSimde/simde_arm_neon_sri_n.hpp>
#import <CppSimde/simde_arm_neon_st1.hpp>
#import <CppSimde/simde_arm_neon_st1_lane.hpp>
#import <CppSimde/simde_arm_neon_st1_x2.hpp>
#import <CppSimde/simde_arm_neon_st1_x3.hpp>
#import <CppSimde/simde_arm_neon_st1_x4.hpp>
#import <CppSimde/simde_arm_neon_st1q_x2.hpp>
#import <CppSimde/simde_arm_neon_st1q_x3.hpp>
#import <CppSimde/simde_arm_neon_st1q_x4.hpp>
#import <CppSimde/simde_arm_neon_st2.hpp>
#import <CppSimde/simde_arm_neon_st2_lane.hpp>
#import <CppSimde/simde_arm_neon_st3.hpp>
#import <CppSimde/simde_arm_neon_st3_lane.hpp>
#import <CppSimde/simde_arm_neon_st4.hpp>
#import <CppSimde/simde_arm_neon_st4_lane.hpp>
#import <CppSimde/simde_arm_neon_sub.hpp>
#import <CppSimde/simde_arm_neon_subhn.hpp>
#import <CppSimde/simde_arm_neon_subhn_high.hpp>
#import <CppSimde/simde_arm_neon_subl.hpp>
#import <CppSimde/simde_arm_neon_subl_high.hpp>
#import <CppSimde/simde_arm_neon_subw.hpp>
#import <CppSimde/simde_arm_neon_subw_high.hpp>
#import <CppSimde/simde_arm_neon_sudot_lane.hpp>
#import <CppSimde/simde_arm_neon_tbl.hpp>
#import <CppSimde/simde_arm_neon_tbx.hpp>
#import <CppSimde/simde_arm_neon_trn.hpp>
#import <CppSimde/simde_arm_neon_trn1.hpp>
#import <CppSimde/simde_arm_neon_trn2.hpp>
#import <CppSimde/simde_arm_neon_tst.hpp>
#import <CppSimde/simde_arm_neon_types.hpp>
#import <CppSimde/simde_arm_neon_uqadd.hpp>
#import <CppSimde/simde_arm_neon_usdot.hpp>
#import <CppSimde/simde_arm_neon_usdot_lane.hpp>
#import <CppSimde/simde_arm_neon_uzp.hpp>
#import <CppSimde/simde_arm_neon_uzp1.hpp>
#import <CppSimde/simde_arm_neon_uzp2.hpp>
#import <CppSimde/simde_arm_neon_xar.hpp>
#import <CppSimde/simde_arm_neon_zip.hpp>
#import <CppSimde/simde_arm_neon_zip1.hpp>
#import <CppSimde/simde_arm_neon_zip2.hpp>
#import <CppSimde/simde_arm_neon.hpp>
#import <CppSimde/simde_arm_sve_add.hpp>
#import <CppSimde/simde_arm_sve_and.hpp>
#import <CppSimde/simde_arm_sve_cmplt.hpp>
#import <CppSimde/simde_arm_sve_cnt.hpp>
#import <CppSimde/simde_arm_sve_dup.hpp>
#import <CppSimde/simde_arm_sve_ld1.hpp>
#import <CppSimde/simde_arm_sve_ptest.hpp>
#import <CppSimde/simde_arm_sve_ptrue.hpp>
#import <CppSimde/simde_arm_sve_qadd.hpp>
#import <CppSimde/simde_arm_sve_reinterpret.hpp>
#import <CppSimde/simde_arm_sve_sel.hpp>
#import <CppSimde/simde_arm_sve_st1.hpp>
#import <CppSimde/simde_arm_sve_sub.hpp>
#import <CppSimde/simde_arm_sve_types.hpp>
#import <CppSimde/simde_arm_sve_whilelt.hpp>
#import <CppSimde/simde_arm_sve.hpp>
#import <CppSimde/simde_check.hpp>
#import <CppSimde/simde_debug-trap.hpp>
#import <CppSimde/simde_hedley.hpp>
#import <CppSimde/simde_mips_msa_add_a.hpp>
#import <CppSimde/simde_mips_msa_adds.hpp>
#import <CppSimde/simde_mips_msa_adds_a.hpp>
#import <CppSimde/simde_mips_msa_addv.hpp>
#import <CppSimde/simde_mips_msa_addvi.hpp>
#import <CppSimde/simde_mips_msa_and.hpp>
#import <CppSimde/simde_mips_msa_andi.hpp>
#import <CppSimde/simde_mips_msa_ld.hpp>
#import <CppSimde/simde_mips_msa_madd.hpp>
#import <CppSimde/simde_mips_msa_st.hpp>
#import <CppSimde/simde_mips_msa_subv.hpp>
#import <CppSimde/simde_mips_msa_types.hpp>
#import <CppSimde/simde_mips_msa.hpp>
#import <CppSimde/simde_simde-aes.hpp>
#import <CppSimde/simde_simde-align.hpp>
#import <CppSimde/simde_simde-arch.hpp>
#import <CppSimde/simde_simde-bf16.hpp>
#import <CppSimde/simde_simde-common.hpp>
#import <CppSimde/simde_simde-complex.hpp>
#import <CppSimde/simde_simde-constify.hpp>
#import <CppSimde/simde_simde-detect-clang.hpp>
#import <CppSimde/simde_simde-diagnostic.hpp>
#import <CppSimde/simde_simde-f16.hpp>
#import <CppSimde/simde_simde-features.hpp>
#import <CppSimde/simde_simde-math.hpp>
#import <CppSimde/simde_wasm_relaxed-simd.hpp>
#import <CppSimde/simde_wasm_simd128.hpp>
#import <CppSimde/simde_x86_aes.hpp>
#import <CppSimde/simde_x86_avx.hpp>
#import <CppSimde/simde_x86_avx2.hpp>
#import <CppSimde/simde_x86_avx512_2intersect.hpp>
#import <CppSimde/simde_x86_avx512_4dpwssd.hpp>
#import <CppSimde/simde_x86_avx512_4dpwssds.hpp>
#import <CppSimde/simde_x86_avx512_abs.hpp>
#import <CppSimde/simde_x86_avx512_add.hpp>
#import <CppSimde/simde_x86_avx512_adds.hpp>
#import <CppSimde/simde_x86_avx512_and.hpp>
#import <CppSimde/simde_x86_avx512_andnot.hpp>
#import <CppSimde/simde_x86_avx512_avg.hpp>
#import <CppSimde/simde_x86_avx512_bitshuffle.hpp>
#import <CppSimde/simde_x86_avx512_blend.hpp>
#import <CppSimde/simde_x86_avx512_broadcast.hpp>
#import <CppSimde/simde_x86_avx512_cast.hpp>
#import <CppSimde/simde_x86_avx512_cmp.hpp>
#import <CppSimde/simde_x86_avx512_cmpeq.hpp>
#import <CppSimde/simde_x86_avx512_cmpge.hpp>
#import <CppSimde/simde_x86_avx512_cmpgt.hpp>
#import <CppSimde/simde_x86_avx512_cmple.hpp>
#import <CppSimde/simde_x86_avx512_cmplt.hpp>
#import <CppSimde/simde_x86_avx512_cmpneq.hpp>
#import <CppSimde/simde_x86_avx512_compress.hpp>
#import <CppSimde/simde_x86_avx512_conflict.hpp>
#import <CppSimde/simde_x86_avx512_copysign.hpp>
#import <CppSimde/simde_x86_avx512_cvt.hpp>
#import <CppSimde/simde_x86_avx512_cvts.hpp>
#import <CppSimde/simde_x86_avx512_cvtt.hpp>
#import <CppSimde/simde_x86_avx512_cvtus.hpp>
#import <CppSimde/simde_x86_avx512_dbsad.hpp>
#import <CppSimde/simde_x86_avx512_div.hpp>
#import <CppSimde/simde_x86_avx512_dpbf16.hpp>
#import <CppSimde/simde_x86_avx512_dpbusd.hpp>
#import <CppSimde/simde_x86_avx512_dpbusds.hpp>
#import <CppSimde/simde_x86_avx512_dpwssd.hpp>
#import <CppSimde/simde_x86_avx512_dpwssds.hpp>
#import <CppSimde/simde_x86_avx512_expand.hpp>
#import <CppSimde/simde_x86_avx512_extract.hpp>
#import <CppSimde/simde_x86_avx512_fixupimm.hpp>
#import <CppSimde/simde_x86_avx512_fixupimm_round.hpp>
#import <CppSimde/simde_x86_avx512_flushsubnormal.hpp>
#import <CppSimde/simde_x86_avx512_fmadd.hpp>
#import <CppSimde/simde_x86_avx512_fmsub.hpp>
#import <CppSimde/simde_x86_avx512_fnmadd.hpp>
#import <CppSimde/simde_x86_avx512_fnmsub.hpp>
#import <CppSimde/simde_x86_avx512_fpclass.hpp>
#import <CppSimde/simde_x86_avx512_gather.hpp>
#import <CppSimde/simde_x86_avx512_insert.hpp>
#import <CppSimde/simde_x86_avx512_kand.hpp>
#import <CppSimde/simde_x86_avx512_knot.hpp>
#import <CppSimde/simde_x86_avx512_kshift.hpp>
#import <CppSimde/simde_x86_avx512_kxor.hpp>
#import <CppSimde/simde_x86_avx512_load.hpp>
#import <CppSimde/simde_x86_avx512_loadu.hpp>
#import <CppSimde/simde_x86_avx512_lzcnt.hpp>
#import <CppSimde/simde_x86_avx512_madd.hpp>
#import <CppSimde/simde_x86_avx512_maddubs.hpp>
#import <CppSimde/simde_x86_avx512_max.hpp>
#import <CppSimde/simde_x86_avx512_min.hpp>
#import <CppSimde/simde_x86_avx512_mov.hpp>
#import <CppSimde/simde_x86_avx512_mov_mask.hpp>
#import <CppSimde/simde_x86_avx512_movm.hpp>
#import <CppSimde/simde_x86_avx512_mul.hpp>
#import <CppSimde/simde_x86_avx512_mulhi.hpp>
#import <CppSimde/simde_x86_avx512_mulhrs.hpp>
#import <CppSimde/simde_x86_avx512_mullo.hpp>
#import <CppSimde/simde_x86_avx512_multishift.hpp>
#import <CppSimde/simde_x86_avx512_negate.hpp>
#import <CppSimde/simde_x86_avx512_or.hpp>
#import <CppSimde/simde_x86_avx512_packs.hpp>
#import <CppSimde/simde_x86_avx512_packus.hpp>
#import <CppSimde/simde_x86_avx512_permutex.hpp>
#import <CppSimde/simde_x86_avx512_permutex2var.hpp>
#import <CppSimde/simde_x86_avx512_permutexvar.hpp>
#import <CppSimde/simde_x86_avx512_popcnt.hpp>
#import <CppSimde/simde_x86_avx512_range.hpp>
#import <CppSimde/simde_x86_avx512_range_round.hpp>
#import <CppSimde/simde_x86_avx512_rcp.hpp>
#import <CppSimde/simde_x86_avx512_reduce.hpp>
#import <CppSimde/simde_x86_avx512_rol.hpp>
#import <CppSimde/simde_x86_avx512_rolv.hpp>
#import <CppSimde/simde_x86_avx512_ror.hpp>
#import <CppSimde/simde_x86_avx512_rorv.hpp>
#import <CppSimde/simde_x86_avx512_round.hpp>
#import <CppSimde/simde_x86_avx512_roundscale.hpp>
#import <CppSimde/simde_x86_avx512_roundscale_round.hpp>
#import <CppSimde/simde_x86_avx512_sad.hpp>
#import <CppSimde/simde_x86_avx512_scalef.hpp>
#import <CppSimde/simde_x86_avx512_set.hpp>
#import <CppSimde/simde_x86_avx512_set1.hpp>
#import <CppSimde/simde_x86_avx512_set4.hpp>
#import <CppSimde/simde_x86_avx512_setone.hpp>
#import <CppSimde/simde_x86_avx512_setr.hpp>
#import <CppSimde/simde_x86_avx512_setr4.hpp>
#import <CppSimde/simde_x86_avx512_setzero.hpp>
#import <CppSimde/simde_x86_avx512_shldv.hpp>
#import <CppSimde/simde_x86_avx512_shuffle.hpp>
#import <CppSimde/simde_x86_avx512_sll.hpp>
#import <CppSimde/simde_x86_avx512_slli.hpp>
#import <CppSimde/simde_x86_avx512_sllv.hpp>
#import <CppSimde/simde_x86_avx512_sqrt.hpp>
#import <CppSimde/simde_x86_avx512_sra.hpp>
#import <CppSimde/simde_x86_avx512_srai.hpp>
#import <CppSimde/simde_x86_avx512_srav.hpp>
#import <CppSimde/simde_x86_avx512_srl.hpp>
#import <CppSimde/simde_x86_avx512_srli.hpp>
#import <CppSimde/simde_x86_avx512_srlv.hpp>
#import <CppSimde/simde_x86_avx512_store.hpp>
#import <CppSimde/simde_x86_avx512_storeu.hpp>
#import <CppSimde/simde_x86_avx512_sub.hpp>
#import <CppSimde/simde_x86_avx512_subs.hpp>
#import <CppSimde/simde_x86_avx512_ternarylogic.hpp>
#import <CppSimde/simde_x86_avx512_test.hpp>
#import <CppSimde/simde_x86_avx512_testn.hpp>
#import <CppSimde/simde_x86_avx512_types.hpp>
#import <CppSimde/simde_x86_avx512_unpackhi.hpp>
#import <CppSimde/simde_x86_avx512_unpacklo.hpp>
#import <CppSimde/simde_x86_avx512_xor.hpp>
#import <CppSimde/simde_x86_avx512_xorsign.hpp>
#import <CppSimde/simde_x86_avx512.hpp>
#import <CppSimde/simde_x86_clmul.hpp>
#import <CppSimde/simde_x86_f16c.hpp>
#import <CppSimde/simde_x86_fma.hpp>
#import <CppSimde/simde_x86_gfni.hpp>
#import <CppSimde/simde_x86_mmx.hpp>
#import <CppSimde/simde_x86_sse.hpp>
#import <CppSimde/simde_x86_sse2.hpp>
#import <CppSimde/simde_x86_sse3.hpp>
#import <CppSimde/simde_x86_sse4.1.hpp>
#import <CppSimde/simde_x86_sse4.2.hpp>
#import <CppSimde/simde_x86_ssse3.hpp>
#import <CppSimde/simde_x86_svml.hpp>
#import <CppSimde/simde_x86_xop.hpp>
